name: Linux Self-Hosted CI

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v3

      - name: Show Linux details
        run: |
          echo "Running on self-hosted Linux runner"
          uname -a
