name: Java CI with Oracle JDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java Development Kits built by Oracle
        uses: oracle-actions/setup-java@v1.4.1
        with:
          website: oracle.com
          release: 24
          version: latest
