name: Java CI with Oracle JDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Oracle JDK
        uses: oracle-actions/setup-java@v1.4.1
        with:
          website: oracle.com
          release: 24
          version: latest

      - name: Build and Check
        run: |
          if [ -f "./gradlew" ]; then
            echo "Detected Gradle project"
            chmod +x ./gradlew
            ./gradlew check
          elif [ -f "pom.xml" ]; then
            echo "Detected Maven project"
            mvn checkstyle:checkstyle
          else
            echo "No recognized build file found (gradlew or pom.xml)"
            exit 1
