name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted   # <--- This tells GitHub to use your self-hosted runner
    steps:
      - uses: actions/checkout@v3
      - name: Run a script
        run: echo "Hello from self-hosted runner!"
